// <auto-generated />
using System;
using Banking.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Banking.Infrastructure.Migrations
{
    [DbContext(typeof(BankingDbContext))]
    [Migration("20260601153125_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.16");

            modelBuilder.Entity("Banking.Domain.Entities.Carta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CVV")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Circuito")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ContoId")
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly>("DataScadenza")
                        .HasColumnType("TEXT");

                    b.Property<string>("NumeroCarta")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PinHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PlafondMensile")
                        .HasColumnType("TEXT");

                    b.Property<string>("StatoCarta")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TipoCarta")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ContoId");

                    b.ToTable("Carte");
                });

            modelBuilder.Entity("Banking.Domain.Entities.Cliente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CodiceCliente")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CodiceFiscale")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Cognome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("DataNascitaCostituzione")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("FilialeId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FilialeRegistrazioneId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("IndirizzoResidenza")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PartitaIva")
                        .HasColumnType("TEXT");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TipoCliente")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("FilialeId");

                    b.ToTable("Clienti");
                });

            modelBuilder.Entity("Banking.Domain.Entities.ContoCorrente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ClienteId")
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly>("DataApertura")
                        .HasColumnType("TEXT");

                    b.Property<string>("IBAN")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("SaldoContabile")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("SaldoDisponibile")
                        .HasColumnType("TEXT");

                    b.Property<string>("StatoConto")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.ToTable("ContiCorrenti");
                });

            modelBuilder.Entity("Banking.Domain.Entities.Dipendente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Cognome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("FilialeId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Matricola")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Ruolo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("FilialeId");

                    b.ToTable("Dipendenti");
                });

            modelBuilder.Entity("Banking.Domain.Entities.DossierTitoli", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ClienteId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CodiceDossier")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("DataApertura")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ValoreTotalePortafoglio")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.ToTable("DossierTitoli");
                });

            modelBuilder.Entity("Banking.Domain.Entities.Filiale", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CAP")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("TEXT");

                    b.Property<string>("Citta")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("CodiceFiliale")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Indirizzo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NomeFiliale")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Filiali");
                });

            modelBuilder.Entity("Banking.Domain.Entities.PortafoglioTitoli", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("DossierId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DossierTitoliId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NomeStrumento")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PrezzoMedioCarico")
                        .HasColumnType("TEXT");

                    b.Property<int>("Quantita")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Ticker")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DossierTitoliId");

                    b.ToTable("PortafoglioTitoli");
                });

            modelBuilder.Entity("Banking.Domain.Entities.Prestito", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("CapitaleResiduo")
                        .HasColumnType("TEXT");

                    b.Property<int>("ClienteId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CodiceContratto")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("DataInizio")
                        .HasColumnType("TEXT");

                    b.Property<int>("DurataMesi")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("ImportoErogato")
                        .HasColumnType("TEXT");

                    b.Property<string>("StatoPrestito")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TassoInteresse")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Prestiti");
                });

            modelBuilder.Entity("Banking.Domain.Entities.RataPrestito", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly>("DataScadenza")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ImportoRata")
                        .HasColumnType("TEXT");

                    b.Property<int>("NumeroRata")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PrestitoId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("StatoPagamento")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PrestitoId");

                    b.ToTable("RatePrestito");
                });

            modelBuilder.Entity("Banking.Domain.Entities.Transazione", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ContoId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DataOra")
                        .HasColumnType("TEXT");

                    b.Property<string>("Descrizione")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("IBANControparte")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Importo")
                        .HasColumnType("TEXT");

                    b.Property<string>("TipoTransazione")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ContoId");

                    b.ToTable("Transazioni");
                });

            modelBuilder.Entity("Banking.Domain.Entities.Carta", b =>
                {
                    b.HasOne("Banking.Domain.Entities.ContoCorrente", "Conto")
                        .WithMany("Carte")
                        .HasForeignKey("ContoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Conto");
                });

            modelBuilder.Entity("Banking.Domain.Entities.Cliente", b =>
                {
                    b.HasOne("Banking.Domain.Entities.Filiale", null)
                        .WithMany("Clienti")
                        .HasForeignKey("FilialeId");
                });

            modelBuilder.Entity("Banking.Domain.Entities.ContoCorrente", b =>
                {
                    b.HasOne("Banking.Domain.Entities.Cliente", "Cliente")
                        .WithMany("Conti")
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("Banking.Domain.Entities.Dipendente", b =>
                {
                    b.HasOne("Banking.Domain.Entities.Filiale", "Filiale")
                        .WithMany("Dipendenti")
                        .HasForeignKey("FilialeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Filiale");
                });

            modelBuilder.Entity("Banking.Domain.Entities.DossierTitoli", b =>
                {
                    b.HasOne("Banking.Domain.Entities.Cliente", "Cliente")
                        .WithMany()
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("Banking.Domain.Entities.PortafoglioTitoli", b =>
                {
                    b.HasOne("Banking.Domain.Entities.DossierTitoli", "DossierTitoli")
                        .WithMany("Titoli")
                        .HasForeignKey("DossierTitoliId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DossierTitoli");
                });

            modelBuilder.Entity("Banking.Domain.Entities.RataPrestito", b =>
                {
                    b.HasOne("Banking.Domain.Entities.Prestito", "Prestito")
                        .WithMany("Rate")
                        .HasForeignKey("PrestitoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Prestito");
                });

            modelBuilder.Entity("Banking.Domain.Entities.Transazione", b =>
                {
                    b.HasOne("Banking.Domain.Entities.ContoCorrente", "Conto")
                        .WithMany("Transazioni")
                        .HasForeignKey("ContoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Conto");
                });

            modelBuilder.Entity("Banking.Domain.Entities.Cliente", b =>
                {
                    b.Navigation("Conti");
                });

            modelBuilder.Entity("Banking.Domain.Entities.ContoCorrente", b =>
                {
                    b.Navigation("Carte");

                    b.Navigation("Transazioni");
                });

            modelBuilder.Entity("Banking.Domain.Entities.DossierTitoli", b =>
                {
                    b.Navigation("Titoli");
                });

            modelBuilder.Entity("Banking.Domain.Entities.Filiale", b =>
                {
                    b.Navigation("Clienti");

                    b.Navigation("Dipendenti");
                });

            modelBuilder.Entity("Banking.Domain.Entities.Prestito", b =>
                {
                    b.Navigation("Rate");
                });
#pragma warning restore 612, 618
        }
    }
}
